# Generated by Django 4.2.6 on 2023-12-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation_condition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_credit', models.IntegerField(default=130)),
                ('total_semester', models.IntegerField(default=8)),
                ('gpa_avg', models.BooleanField(default=True)),
                ('graduation_project', models.BooleanField(default=False)),
                ('important_main', models.IntegerField(default=2)),
                ('basic_elective', models.IntegerField(default=10)),
                ('choice_elective', models.IntegerField(default=15)),
                ('choice_elective_part', models.IntegerField(default=7)),
                ('knowledge_education', models.IntegerField(default=1)),
                ('major_basic_elective', models.IntegerField(default=4)),
                ('major_essential', models.IntegerField(default=27)),
                ('major_choice', models.IntegerField(default=48)),
                ('common_elective', models.IntegerField(default=12)),
            ],
            options={
                'db_table': 'home_graduation_condition',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_major', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'home_student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_semester', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'home_subject',
            },
        ),
        migrations.CreateModel(
            name='Gpa_avg',
            fields=[
                ('gpa_avg_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=10)),
                ('gpa_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('major_gpa_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('semester_credit', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'home_gpa_avg',
            },
        ),
        migrations.CreateModel(
            name='Academic_status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_gpa_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_major_gpa_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_semester', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'home_academic_status',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=10, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'home_semester',
                'unique_together': {('student_id', 'semester')},
            },
        ),
    ]
